package br.pucrio.inf.les.opus.tomicroservices.main;

import java.io.File;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

import br.pucrio.inf.les.opus.tomicroservices.graph.PrintGraph;

public class Main {
	/**
	public static void main(String[] args) {
		Options options = new Options();
		final String logFileOption = "logfile";
		final String numberOfMicroservicesOption = "numbermicroservices";
		final String outputFileOption = "outputfile";
		options.addOption(logFileOption, true, "Path to log file generated by toMicroservices agent");
		options.addOption(numberOfMicroservicesOption, true, "Number of microservices generated");
		options.addOption(outputFileOption, true, "Path to Output file");
		CommandLineParser parser = new DefaultParser();
		try {
			CommandLine cmd = parser.parse(options, args);
			boolean fail = false;
			if (!cmd.hasOption(logFileOption)) {
				System.err.println("There is not " + logFileOption);
				fail = true;
			} 
			if (!cmd.hasOption(numberOfMicroservicesOption)) {
				System.err.println("There is not " + numberOfMicroservicesOption);
				fail = true;
			}
			if (!cmd.hasOption(outputFileOption)) {
				System.err.println("There is not " + outputFileOption);
				fail = true; //TODO - remove code duplication
			}
			if (fail) return;
			String logFilePath = cmd.getOptionValue(logFileOption);
			File logFile = new File(logFilePath);
			String numberMicroservicesStr = cmd.getOptionValue(numberOfMicroservicesOption);
			int nMicroservices = Integer.parseInt(numberMicroservicesStr);
			String outputPath = cmd.getOptionValue(outputFileOption);
			File outputFile = new File(outputPath);
			PrintGraph graph = new PrintGraph();
			graph.print(logFile, outputFile, nMicroservices);
		} catch (ParseException e) {
			e.printStackTrace();
		}
	}
	**/
	
}
